// Code generated by pggen. DO NOT EDIT.

package device

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"net"
)

type QueryName struct{}

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	FindDevicesByUser(ctx context.Context, id int) ([]FindDevicesByUserRow, error)

	CompositeUser(ctx context.Context) ([]CompositeUserRow, error)

	CompositeUserOne(ctx context.Context) (User, error)

	CompositeUserOneTwoCols(ctx context.Context) (CompositeUserOneTwoColsRow, error)

	CompositeUserMany(ctx context.Context) ([]User, error)

	InsertUser(ctx context.Context, userID int, name string) (pgconn.CommandTag, error)

	InsertDevice(ctx context.Context, mac net.HardwareAddr, owner int) (pgconn.CommandTag, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn genericConn
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// NewQuerier creates a DBQuerier that implements Querier.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// User represents the Postgres composite type "user".
type User struct {
	ID   *int    `json:"id" db:"id"`
	Name *string `json:"name" db:"name"`
}

// DeviceType represents the Postgres enum "device_type".
type DeviceType string

const (
	DeviceTypeUndefined DeviceType = "undefined"
	DeviceTypePhone     DeviceType = "phone"
	DeviceTypeLaptop    DeviceType = "laptop"
	DeviceTypeIpad      DeviceType = "ipad"
	DeviceTypeDesktop   DeviceType = "desktop"
	DeviceTypeIot       DeviceType = "iot"
)

func (d DeviceType) String() string { return string(d) }

// RegisterTypes loads custom PostgreSQL types into conn's pgx type map.
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error {
	pending := append([]string(nil), typesToRegister...)
	for len(pending) > 0 {
		remaining := pending[:0]
		loaded := 0
		var lastErr error
		var lastType string
		for _, typ := range pending {
			dt, err := conn.LoadType(ctx, typ)
			if err != nil {
				lastErr = err
				lastType = typ
				remaining = append(remaining, typ)
				continue
			}
			conn.TypeMap().RegisterType(dt)
			loaded++
		}
		if loaded == 0 {
			return fmt.Errorf("load PostgreSQL type %q: %w", lastType, lastErr)
		}
		pending = remaining
	}
	return nil
}

var typesToRegister = []string{}

func addTypeToRegister(typ string) struct{} {
	typesToRegister = append(typesToRegister, typ)
	return struct{}{}
}

var _ = addTypeToRegister("\"device_type\"")

var _ = addTypeToRegister("\"user\"")

const findDevicesByUserSQL = `SELECT
  id,
  name,
  (SELECT array_agg(mac) FROM device WHERE owner = id) AS mac_addrs
FROM "user"
WHERE id = $1;`

type FindDevicesByUserRow struct {
	ID       int                `json:"id" db:"id"`
	Name     string             `json:"name" db:"name"`
	MacAddrs []net.HardwareAddr `json:"mac_addrs" db:"mac_addrs"`
}

// FindDevicesByUser implements Querier.FindDevicesByUser.
func (q *DBQuerier) FindDevicesByUser(ctx context.Context, id int) ([]FindDevicesByUserRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindDevicesByUser")
	rows, err := q.conn.Query(ctx, findDevicesByUserSQL, id)
	if err != nil {
		var zero []FindDevicesByUserRow
		return zero, fmt.Errorf("query FindDevicesByUser: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindDevicesByUserRow])
	if err != nil {
		var zero []FindDevicesByUserRow
		return zero, fmt.Errorf("scan FindDevicesByUser row: %w", err)
	}
	return result, nil
}

const compositeUserSQL = `SELECT
  d.mac,
  d.type,
  ROW (u.id, u.name)::"user" AS "user"
FROM device d
  LEFT JOIN "user" u ON u.id = d.owner;`

type CompositeUserRow struct {
	Mac  net.HardwareAddr `json:"mac" db:"mac"`
	Type DeviceType       `json:"type" db:"type"`
	User User             `json:"user" db:"user"`
}

// CompositeUser implements Querier.CompositeUser.
func (q *DBQuerier) CompositeUser(ctx context.Context) ([]CompositeUserRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CompositeUser")
	rows, err := q.conn.Query(ctx, compositeUserSQL)
	if err != nil {
		var zero []CompositeUserRow
		return zero, fmt.Errorf("query CompositeUser: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[CompositeUserRow])
	if err != nil {
		var zero []CompositeUserRow
		return zero, fmt.Errorf("scan CompositeUser row: %w", err)
	}
	return result, nil
}

const compositeUserOneSQL = `SELECT ROW (15, 'qux')::"user" AS "user";`

// CompositeUserOne implements Querier.CompositeUserOne.
func (q *DBQuerier) CompositeUserOne(ctx context.Context) (User, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CompositeUserOne")
	rows, err := q.conn.Query(ctx, compositeUserOneSQL)
	if err != nil {
		var zero User
		return zero, fmt.Errorf("query CompositeUserOne: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowTo[User])
	if err != nil {
		var zero User
		return zero, fmt.Errorf("query CompositeUserOne: %w", err)
	}
	return result, nil
}

const compositeUserOneTwoColsSQL = `SELECT 1 AS num, ROW (15, 'qux')::"user" AS "user";`

type CompositeUserOneTwoColsRow struct {
	Num  int32 `json:"num" db:"num"`
	User User  `json:"user" db:"user"`
}

// CompositeUserOneTwoCols implements Querier.CompositeUserOneTwoCols.
func (q *DBQuerier) CompositeUserOneTwoCols(ctx context.Context) (CompositeUserOneTwoColsRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CompositeUserOneTwoCols")
	rows, err := q.conn.Query(ctx, compositeUserOneTwoColsSQL)
	if err != nil {
		var zero CompositeUserOneTwoColsRow
		return zero, fmt.Errorf("query CompositeUserOneTwoCols: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[CompositeUserOneTwoColsRow])
	if err != nil {
		var zero CompositeUserOneTwoColsRow
		return zero, fmt.Errorf("query CompositeUserOneTwoCols: %w", err)
	}
	return result, nil
}

const compositeUserManySQL = `SELECT ROW (15, 'qux')::"user" AS "user";`

// CompositeUserMany implements Querier.CompositeUserMany.
func (q *DBQuerier) CompositeUserMany(ctx context.Context) ([]User, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CompositeUserMany")
	rows, err := q.conn.Query(ctx, compositeUserManySQL)
	if err != nil {
		var zero []User
		return zero, fmt.Errorf("query CompositeUserMany: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowTo[User])
	if err != nil {
		var zero []User
		return zero, fmt.Errorf("scan CompositeUserMany row: %w", err)
	}
	return result, nil
}

const insertUserSQL = `INSERT INTO "user" (id, name)
VALUES ($1, $2);`

// InsertUser implements Querier.InsertUser.
func (q *DBQuerier) InsertUser(ctx context.Context, userID int, name string) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, QueryName{}, "InsertUser")
	cmdTag, err := q.conn.Exec(ctx, insertUserSQL, userID, name)
	if err != nil {
		return pgconn.CommandTag{}, fmt.Errorf("exec query InsertUser: %w", err)
	}
	return cmdTag, err
}

const insertDeviceSQL = `INSERT INTO device (mac, owner)
VALUES ($1, $2);`

// InsertDevice implements Querier.InsertDevice.
func (q *DBQuerier) InsertDevice(ctx context.Context, mac net.HardwareAddr, owner int) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, QueryName{}, "InsertDevice")
	cmdTag, err := q.conn.Exec(ctx, insertDeviceSQL, mac, owner)
	if err != nil {
		return pgconn.CommandTag{}, fmt.Errorf("exec query InsertDevice: %w", err)
	}
	return cmdTag, err
}
