// Code generated by pggen. DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type QueryName struct{}

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	CreateTenant(ctx context.Context, key string, name string) (CreateTenantRow, error)

	FindOrdersByCustomer(ctx context.Context, customerID int32) ([]FindOrdersByCustomerRow, error)

	FindProductsInOrder(ctx context.Context, orderID int32) ([]FindProductsInOrderRow, error)

	InsertCustomer(ctx context.Context, params InsertCustomerParams) (InsertCustomerRow, error)

	InsertOrder(ctx context.Context, params InsertOrderParams) (InsertOrderRow, error)

	FindOrdersByPrice(ctx context.Context, minTotal pgtype.Numeric) ([]FindOrdersByPriceRow, error)

	FindOrdersMRR(ctx context.Context) ([]FindOrdersMRRRow, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn genericConn
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// NewQuerier creates a DBQuerier that implements Querier.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// RegisterTypes loads custom PostgreSQL types into conn's pgx type map.
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error {
	pending := append([]string(nil), typesToRegister...)
	for len(pending) > 0 {
		remaining := pending[:0]
		loaded := 0
		var lastErr error
		var lastType string
		for _, typ := range pending {
			dt, err := conn.LoadType(ctx, typ)
			if err != nil {
				lastErr = err
				lastType = typ
				remaining = append(remaining, typ)
				continue
			}
			conn.TypeMap().RegisterType(dt)
			loaded++
		}
		if loaded == 0 {
			return fmt.Errorf("load PostgreSQL type %q: %w", lastType, lastErr)
		}
		pending = remaining
	}
	return nil
}

var typesToRegister = []string{}

func addTypeToRegister(typ string) struct{} {
	typesToRegister = append(typesToRegister, typ)
	return struct{}{}
}

const createTenantSQL = `INSERT INTO tenant (tenant_id, name)
VALUES (base36_decode($1::text)::tenant_id, $2::text)
RETURNING *;`

type CreateTenantProjection interface {
	GetTenantID() int
	GetRname() *string
	GetName() string
}

type CreateTenantRow struct {
	TenantID int     `json:"tenant_id" db:"tenant_id"`
	Rname    *string `json:"rname" db:"rname"`
	Name     string  `json:"name" db:"name"`
}

func (r *CreateTenantRow) GetTenantID() int { return r.TenantID }

func (r *CreateTenantRow) GetRname() *string { return r.Rname }

func (r *CreateTenantRow) GetName() string { return r.Name }

// CreateTenant implements Querier.CreateTenant.
func (q *DBQuerier) CreateTenant(ctx context.Context, key string, name string) (CreateTenantRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CreateTenant")
	rows, err := q.conn.Query(ctx, createTenantSQL, key, name)
	if err != nil {
		var zero CreateTenantRow
		return zero, fmt.Errorf("query CreateTenant: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[CreateTenantRow])
	if err != nil {
		var zero CreateTenantRow
		return zero, fmt.Errorf("query CreateTenant: %w", err)
	}
	return result, nil
}

const findOrdersByCustomerSQL = `SELECT *
FROM orders
WHERE customer_id = $1;`

type FindOrdersByCustomerProjection interface {
	GetOrderID() int32
	GetOrderDate() pgtype.Timestamptz
	GetOrderTotal() pgtype.Numeric
	GetCustomerID() *int32
}

type FindOrdersByCustomerRow struct {
	OrderID    int32              `json:"order_id" db:"order_id"`
	OrderDate  pgtype.Timestamptz `json:"order_date" db:"order_date"`
	OrderTotal pgtype.Numeric     `json:"order_total" db:"order_total"`
	CustomerID *int32             `json:"customer_id" db:"customer_id"`
}

func (r *FindOrdersByCustomerRow) GetOrderID() int32 { return r.OrderID }

func (r *FindOrdersByCustomerRow) GetOrderDate() pgtype.Timestamptz { return r.OrderDate }

func (r *FindOrdersByCustomerRow) GetOrderTotal() pgtype.Numeric { return r.OrderTotal }

func (r *FindOrdersByCustomerRow) GetCustomerID() *int32 { return r.CustomerID }

// FindOrdersByCustomer implements Querier.FindOrdersByCustomer.
func (q *DBQuerier) FindOrdersByCustomer(ctx context.Context, customerID int32) ([]FindOrdersByCustomerRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindOrdersByCustomer")
	rows, err := q.conn.Query(ctx, findOrdersByCustomerSQL, customerID)
	if err != nil {
		var zero []FindOrdersByCustomerRow
		return zero, fmt.Errorf("query FindOrdersByCustomer: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindOrdersByCustomerRow])
	if err != nil {
		var zero []FindOrdersByCustomerRow
		return zero, fmt.Errorf("scan FindOrdersByCustomer row: %w", err)
	}
	return result, nil
}

const findProductsInOrderSQL = `SELECT o.order_id, p.product_id, p.name
FROM orders o
  INNER JOIN order_product op USING (order_id)
  INNER JOIN product p USING (product_id)
WHERE o.order_id = $1;`

type FindProductsInOrderProjection interface {
	GetOrderID() *int32
	GetProductID() *int32
	GetName() *string
}

type FindProductsInOrderRow struct {
	OrderID   *int32  `json:"order_id" db:"order_id"`
	ProductID *int32  `json:"product_id" db:"product_id"`
	Name      *string `json:"name" db:"name"`
}

func (r *FindProductsInOrderRow) GetOrderID() *int32 { return r.OrderID }

func (r *FindProductsInOrderRow) GetProductID() *int32 { return r.ProductID }

func (r *FindProductsInOrderRow) GetName() *string { return r.Name }

// FindProductsInOrder implements Querier.FindProductsInOrder.
func (q *DBQuerier) FindProductsInOrder(ctx context.Context, orderID int32) ([]FindProductsInOrderRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindProductsInOrder")
	rows, err := q.conn.Query(ctx, findProductsInOrderSQL, orderID)
	if err != nil {
		var zero []FindProductsInOrderRow
		return zero, fmt.Errorf("query FindProductsInOrder: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindProductsInOrderRow])
	if err != nil {
		var zero []FindProductsInOrderRow
		return zero, fmt.Errorf("scan FindProductsInOrder row: %w", err)
	}
	return result, nil
}

const insertCustomerSQL = `INSERT INTO customer (first_name, last_name, email)
VALUES ($1, $2, $3)
RETURNING *;`

type InsertCustomerParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

type InsertCustomerProjection interface {
	GetCustomerID() int32
	GetFirstName() string
	GetLastName() string
	GetEmail() string
}

type InsertCustomerRow struct {
	CustomerID int32  `json:"customer_id" db:"customer_id"`
	FirstName  string `json:"first_name" db:"first_name"`
	LastName   string `json:"last_name" db:"last_name"`
	Email      string `json:"email" db:"email"`
}

func (r *InsertCustomerRow) GetCustomerID() int32 { return r.CustomerID }

func (r *InsertCustomerRow) GetFirstName() string { return r.FirstName }

func (r *InsertCustomerRow) GetLastName() string { return r.LastName }

func (r *InsertCustomerRow) GetEmail() string { return r.Email }

// InsertCustomer implements Querier.InsertCustomer.
func (q *DBQuerier) InsertCustomer(ctx context.Context, params InsertCustomerParams) (InsertCustomerRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "InsertCustomer")
	rows, err := q.conn.Query(ctx, insertCustomerSQL, params.FirstName, params.LastName, params.Email)
	if err != nil {
		var zero InsertCustomerRow
		return zero, fmt.Errorf("query InsertCustomer: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[InsertCustomerRow])
	if err != nil {
		var zero InsertCustomerRow
		return zero, fmt.Errorf("query InsertCustomer: %w", err)
	}
	return result, nil
}

const insertOrderSQL = `INSERT INTO orders (order_date, order_total, customer_id)
VALUES ($1, $2, $3)
RETURNING *;`

type InsertOrderParams struct {
	OrderDate  pgtype.Timestamptz `json:"order_date"`
	OrderTotal pgtype.Numeric     `json:"order_total"`
	CustID     int32              `json:"cust_id"`
}

type InsertOrderProjection interface {
	GetOrderID() int32
	GetOrderDate() pgtype.Timestamptz
	GetOrderTotal() pgtype.Numeric
	GetCustomerID() *int32
}

type InsertOrderRow struct {
	OrderID    int32              `json:"order_id" db:"order_id"`
	OrderDate  pgtype.Timestamptz `json:"order_date" db:"order_date"`
	OrderTotal pgtype.Numeric     `json:"order_total" db:"order_total"`
	CustomerID *int32             `json:"customer_id" db:"customer_id"`
}

func (r *InsertOrderRow) GetOrderID() int32 { return r.OrderID }

func (r *InsertOrderRow) GetOrderDate() pgtype.Timestamptz { return r.OrderDate }

func (r *InsertOrderRow) GetOrderTotal() pgtype.Numeric { return r.OrderTotal }

func (r *InsertOrderRow) GetCustomerID() *int32 { return r.CustomerID }

// InsertOrder implements Querier.InsertOrder.
func (q *DBQuerier) InsertOrder(ctx context.Context, params InsertOrderParams) (InsertOrderRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "InsertOrder")
	rows, err := q.conn.Query(ctx, insertOrderSQL, params.OrderDate, params.OrderTotal, params.CustID)
	if err != nil {
		var zero InsertOrderRow
		return zero, fmt.Errorf("query InsertOrder: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[InsertOrderRow])
	if err != nil {
		var zero InsertOrderRow
		return zero, fmt.Errorf("query InsertOrder: %w", err)
	}
	return result, nil
}
