// Code generated by pggen. DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const findOrdersByPriceSQL = `SELECT * FROM orders WHERE order_total > $1;`

// FindOrdersByPrice implements Querier.FindOrdersByPrice.
func (q *DBQuerier) FindOrdersByPrice(ctx context.Context, minTotal pgtype.Numeric) ([]OrderRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindOrdersByPrice")
	rows, err := q.conn.Query(ctx, findOrdersByPriceSQL, minTotal)
	if err != nil {
		var zero []OrderRow
		return zero, fmt.Errorf("query FindOrdersByPrice: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[OrderRow])
	if err != nil {
		var zero []OrderRow
		return zero, fmt.Errorf("scan FindOrdersByPrice row: %w", err)
	}
	return result, nil
}

const findOrdersMRRSQL = `SELECT date_trunc('month', order_date) AS month, sum(order_total) AS order_mrr
FROM orders
GROUP BY date_trunc('month', order_date);`

type FindOrdersMRRRow struct {
	Month    pgtype.Timestamptz `json:"month" db:"month"`
	OrderMRR pgtype.Numeric     `json:"order_mrr" db:"order_mrr"`
}

// FindOrdersMRR implements Querier.FindOrdersMRR.
func (q *DBQuerier) FindOrdersMRR(ctx context.Context) ([]FindOrdersMRRRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindOrdersMRR")
	rows, err := q.conn.Query(ctx, findOrdersMRRSQL)
	if err != nil {
		var zero []FindOrdersMRRRow
		return zero, fmt.Errorf("query FindOrdersMRR: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindOrdersMRRRow])
	if err != nil {
		var zero []FindOrdersMRRRow
		return zero, fmt.Errorf("scan FindOrdersMRR row: %w", err)
	}
	return result, nil
}
