// Code generated by pggen. DO NOT EDIT.

package enums

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"net"
)

type QueryName struct{}

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	FindAllDevices(ctx context.Context) ([]FindAllDevicesRow, error)

	InsertDevice(ctx context.Context, mac net.HardwareAddr, typePg DeviceType) (pgconn.CommandTag, error)

	// Select an array of all device_type enum values.
	FindOneDeviceArray(ctx context.Context) ([]DeviceType, error)

	// Select many rows of device_type enum values.
	FindManyDeviceArray(ctx context.Context) ([][]DeviceType, error)

	// Select many rows of device_type enum values with multiple output columns.
	FindManyDeviceArrayWithNum(ctx context.Context) ([]FindManyDeviceArrayWithNumRow, error)

	// Regression test for https://github.com/meoyawn/pggen/issues/23.
	EnumInsideComposite(ctx context.Context) (Device, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn genericConn
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// NewQuerier creates a DBQuerier that implements Querier.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// Device represents the Postgres composite type "device".
type Device struct {
	Mac  net.HardwareAddr `json:"mac" db:"mac"`
	Type DeviceType       `json:"type" db:"type"`
}

// DeviceType represents the Postgres enum "device_type".
type DeviceType string

const (
	DeviceTypeUndefined DeviceType = "undefined"
	DeviceTypePhone     DeviceType = "phone"
	DeviceTypeLaptop    DeviceType = "laptop"
	DeviceTypeIpad      DeviceType = "ipad"
	DeviceTypeDesktop   DeviceType = "desktop"
	DeviceTypeIot       DeviceType = "iot"
)

func (d DeviceType) String() string { return string(d) }

// RegisterTypes loads custom PostgreSQL types into conn's pgx type map.
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error {
	pending := append([]string(nil), typesToRegister...)
	for len(pending) > 0 {
		remaining := pending[:0]
		loaded := 0
		var lastErr error
		var lastType string
		for _, typ := range pending {
			dt, err := conn.LoadType(ctx, typ)
			if err != nil {
				lastErr = err
				lastType = typ
				remaining = append(remaining, typ)
				continue
			}
			conn.TypeMap().RegisterType(dt)
			loaded++
		}
		if loaded == 0 {
			return fmt.Errorf("load PostgreSQL type %q: %w", lastType, lastErr)
		}
		pending = remaining
	}
	return nil
}

var typesToRegister = []string{}

func addTypeToRegister(typ string) struct{} {
	typesToRegister = append(typesToRegister, typ)
	return struct{}{}
}

var _ = addTypeToRegister("\"device_type\"")

var _ = addTypeToRegister("\"device\"")

var _ = addTypeToRegister("\"_device_type\"")

const findAllDevicesSQL = `SELECT mac, type
FROM device;`

type FindAllDevicesProjection interface {
	GetMac() net.HardwareAddr
	GetType() DeviceType
}

type FindAllDevicesRow struct {
	Mac  net.HardwareAddr `json:"mac" db:"mac"`
	Type DeviceType       `json:"type" db:"type"`
}

func (r FindAllDevicesRow) GetMac() net.HardwareAddr { return r.Mac }

func (r FindAllDevicesRow) GetType() DeviceType { return r.Type }

// FindAllDevices implements Querier.FindAllDevices.
func (q *DBQuerier) FindAllDevices(ctx context.Context) ([]FindAllDevicesRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindAllDevices")
	rows, err := q.conn.Query(ctx, findAllDevicesSQL)
	if err != nil {
		var zero []FindAllDevicesRow
		return zero, fmt.Errorf("query FindAllDevices: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindAllDevicesRow])
	if err != nil {
		var zero []FindAllDevicesRow
		return zero, fmt.Errorf("scan FindAllDevices row: %w", err)
	}
	return result, nil
}

const insertDeviceSQL = `INSERT INTO device (mac, type)
VALUES ($1, $2);`

// InsertDevice implements Querier.InsertDevice.
func (q *DBQuerier) InsertDevice(ctx context.Context, mac net.HardwareAddr, typePg DeviceType) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, QueryName{}, "InsertDevice")
	cmdTag, err := q.conn.Exec(ctx, insertDeviceSQL, mac, typePg)
	if err != nil {
		return pgconn.CommandTag{}, fmt.Errorf("exec query InsertDevice: %w", err)
	}
	return cmdTag, err
}

const findOneDeviceArraySQL = `SELECT enum_range(NULL::device_type) AS device_types;`

// FindOneDeviceArray implements Querier.FindOneDeviceArray.
func (q *DBQuerier) FindOneDeviceArray(ctx context.Context) ([]DeviceType, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindOneDeviceArray")
	rows, err := q.conn.Query(ctx, findOneDeviceArraySQL)
	if err != nil {
		var zero []DeviceType
		return zero, fmt.Errorf("query FindOneDeviceArray: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowTo[[]DeviceType])
	if err != nil {
		var zero []DeviceType
		return zero, fmt.Errorf("query FindOneDeviceArray: %w", err)
	}
	return result, nil
}

const findManyDeviceArraySQL = `SELECT enum_range('ipad'::device_type, 'iot'::device_type) AS device_types
UNION ALL
SELECT enum_range(NULL::device_type) AS device_types;`

// FindManyDeviceArray implements Querier.FindManyDeviceArray.
func (q *DBQuerier) FindManyDeviceArray(ctx context.Context) ([][]DeviceType, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindManyDeviceArray")
	rows, err := q.conn.Query(ctx, findManyDeviceArraySQL)
	if err != nil {
		var zero [][]DeviceType
		return zero, fmt.Errorf("query FindManyDeviceArray: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowTo[[]DeviceType])
	if err != nil {
		var zero [][]DeviceType
		return zero, fmt.Errorf("scan FindManyDeviceArray row: %w", err)
	}
	return result, nil
}

const findManyDeviceArrayWithNumSQL = `SELECT 1 AS num, enum_range('ipad'::device_type, 'iot'::device_type) AS device_types
UNION ALL
SELECT 2 as num, enum_range(NULL::device_type) AS device_types;`

type FindManyDeviceArrayWithNumProjection interface {
	GetNum() *int32
	GetDeviceTypes() []DeviceType
}

type FindManyDeviceArrayWithNumRow struct {
	Num         *int32       `json:"num" db:"num"`
	DeviceTypes []DeviceType `json:"device_types" db:"device_types"`
}

func (r FindManyDeviceArrayWithNumRow) GetNum() *int32 { return r.Num }

func (r FindManyDeviceArrayWithNumRow) GetDeviceTypes() []DeviceType { return r.DeviceTypes }

// FindManyDeviceArrayWithNum implements Querier.FindManyDeviceArrayWithNum.
func (q *DBQuerier) FindManyDeviceArrayWithNum(ctx context.Context) ([]FindManyDeviceArrayWithNumRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindManyDeviceArrayWithNum")
	rows, err := q.conn.Query(ctx, findManyDeviceArrayWithNumSQL)
	if err != nil {
		var zero []FindManyDeviceArrayWithNumRow
		return zero, fmt.Errorf("query FindManyDeviceArrayWithNum: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindManyDeviceArrayWithNumRow])
	if err != nil {
		var zero []FindManyDeviceArrayWithNumRow
		return zero, fmt.Errorf("scan FindManyDeviceArrayWithNum row: %w", err)
	}
	return result, nil
}

const enumInsideCompositeSQL = `SELECT ROW('08:00:2b:01:02:03'::macaddr, 'phone'::device_type) ::device;`

// EnumInsideComposite implements Querier.EnumInsideComposite.
func (q *DBQuerier) EnumInsideComposite(ctx context.Context) (Device, error) {
	ctx = context.WithValue(ctx, QueryName{}, "EnumInsideComposite")
	rows, err := q.conn.Query(ctx, enumInsideCompositeSQL)
	if err != nil {
		var zero Device
		return zero, fmt.Errorf("query EnumInsideComposite: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowTo[Device])
	if err != nil {
		var zero Device
		return zero, fmt.Errorf("query EnumInsideComposite: %w", err)
	}
	return result, nil
}
