// Code generated by pggen. DO NOT EDIT.

package complex_params

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type QueryName struct{}

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	ParamArrayInt(ctx context.Context, ints []int) ([]int, error)

	ParamNested1(ctx context.Context, dimensions Dimensions) (Dimensions, error)

	ParamNested2(ctx context.Context, image ProductImageType) (ProductImageType, error)

	ParamNested2Array(ctx context.Context, images []ProductImageType) ([]ProductImageType, error)

	ParamNested3(ctx context.Context, imageSet ProductImageSetType) (ProductImageSetType, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn genericConn
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// NewQuerier creates a DBQuerier that implements Querier.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// Dimensions represents the Postgres composite type "dimensions".
type Dimensions struct {
	Width  int `json:"width" db:"width"`
	Height int `json:"height" db:"height"`
}

// ProductImageSetType represents the Postgres composite type "product_image_set_type".
type ProductImageSetType struct {
	Name      string             `json:"name" db:"name"`
	OrigImage ProductImageType   `json:"orig_image" db:"orig_image"`
	Images    []ProductImageType `json:"images" db:"images"`
}

// ProductImageType represents the Postgres composite type "product_image_type".
type ProductImageType struct {
	Source     string     `json:"source" db:"source"`
	Dimensions Dimensions `json:"dimensions" db:"dimensions"`
}

// RegisterTypes loads custom PostgreSQL types into conn's pgx type map.
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error {
	pending := append([]string(nil), typesToRegister...)
	for len(pending) > 0 {
		remaining := pending[:0]
		loaded := 0
		var lastErr error
		var lastType string
		for _, typ := range pending {
			dt, err := conn.LoadType(ctx, typ)
			if err != nil {
				lastErr = err
				lastType = typ
				remaining = append(remaining, typ)
				continue
			}
			conn.TypeMap().RegisterType(dt)
			loaded++
		}
		if loaded == 0 {
			return fmt.Errorf("load PostgreSQL type %q: %w", lastType, lastErr)
		}
		pending = remaining
	}
	return nil
}

var typesToRegister = []string{}

func addTypeToRegister(typ string) struct{} {
	typesToRegister = append(typesToRegister, typ)
	return struct{}{}
}

var _ = addTypeToRegister("\"dimensions\"")

var _ = addTypeToRegister("\"product_image_set_type\"")

var _ = addTypeToRegister("\"product_image_type\"")

var _ = addTypeToRegister("\"_product_image_type\"")

const paramArrayIntSQL = `SELECT $1::bigint[];`

// ParamArrayInt implements Querier.ParamArrayInt.
func (q *DBQuerier) ParamArrayInt(ctx context.Context, ints []int) ([]int, error) {
	ctx = context.WithValue(ctx, QueryName{}, "ParamArrayInt")
	rows, err := q.conn.Query(ctx, paramArrayIntSQL, ints)
	if err != nil {
		var zero []int
		return zero, fmt.Errorf("query ParamArrayInt: %w", err)
	}

	return pgx.CollectOneRow(rows, pgx.RowTo[[]int])
}

const paramNested1SQL = `SELECT $1::dimensions;`

// ParamNested1 implements Querier.ParamNested1.
func (q *DBQuerier) ParamNested1(ctx context.Context, dimensions Dimensions) (Dimensions, error) {
	ctx = context.WithValue(ctx, QueryName{}, "ParamNested1")
	rows, err := q.conn.Query(ctx, paramNested1SQL, dimensions)
	if err != nil {
		var zero Dimensions
		return zero, fmt.Errorf("query ParamNested1: %w", err)
	}

	return pgx.CollectOneRow(rows, pgx.RowTo[Dimensions])
}

const paramNested2SQL = `SELECT $1::product_image_type;`

// ParamNested2 implements Querier.ParamNested2.
func (q *DBQuerier) ParamNested2(ctx context.Context, image ProductImageType) (ProductImageType, error) {
	ctx = context.WithValue(ctx, QueryName{}, "ParamNested2")
	rows, err := q.conn.Query(ctx, paramNested2SQL, image)
	if err != nil {
		var zero ProductImageType
		return zero, fmt.Errorf("query ParamNested2: %w", err)
	}

	return pgx.CollectOneRow(rows, pgx.RowTo[ProductImageType])
}

const paramNested2ArraySQL = `SELECT $1::product_image_type[];`

// ParamNested2Array implements Querier.ParamNested2Array.
func (q *DBQuerier) ParamNested2Array(ctx context.Context, images []ProductImageType) ([]ProductImageType, error) {
	ctx = context.WithValue(ctx, QueryName{}, "ParamNested2Array")
	rows, err := q.conn.Query(ctx, paramNested2ArraySQL, images)
	if err != nil {
		var zero []ProductImageType
		return zero, fmt.Errorf("query ParamNested2Array: %w", err)
	}

	return pgx.CollectOneRow(rows, pgx.RowTo[[]ProductImageType])
}

const paramNested3SQL = `SELECT $1::product_image_set_type;`

// ParamNested3 implements Querier.ParamNested3.
func (q *DBQuerier) ParamNested3(ctx context.Context, imageSet ProductImageSetType) (ProductImageSetType, error) {
	ctx = context.WithValue(ctx, QueryName{}, "ParamNested3")
	rows, err := q.conn.Query(ctx, paramNested3SQL, imageSet)
	if err != nil {
		var zero ProductImageSetType
		return zero, fmt.Errorf("query ParamNested3: %w", err)
	}

	return pgx.CollectOneRow(rows, pgx.RowTo[ProductImageSetType])
}
