// Code generated by pggen. DO NOT EDIT.

package custom_types

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jschaf/pggen/example/custom_types/mytype"
)

type QueryName struct{}

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	CustomTypes(ctx context.Context) (CustomTypesRow, error)

	CustomString(ctx context.Context) (mytype.String, error)

	CustomMyInt(ctx context.Context) (int, error)

	IntArray(ctx context.Context) ([][]int32, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn genericConn
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// NewQuerier creates a DBQuerier that implements Querier.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn}
}

// RegisterTypes loads custom PostgreSQL types into conn's pgx type map.
func RegisterTypes(ctx context.Context, conn *pgx.Conn) error {
	pending := append([]string(nil), typesToRegister...)
	for len(pending) > 0 {
		remaining := pending[:0]
		loaded := 0
		var lastErr error
		var lastType string
		for _, typ := range pending {
			dt, err := conn.LoadType(ctx, typ)
			if err != nil {
				lastErr = err
				lastType = typ
				remaining = append(remaining, typ)
				continue
			}
			conn.TypeMap().RegisterType(dt)
			loaded++
		}
		if loaded == 0 {
			return fmt.Errorf("load PostgreSQL type %q: %w", lastType, lastErr)
		}
		pending = remaining
	}
	return nil
}

var typesToRegister = []string{}

func addTypeToRegister(typ string) struct{} {
	typesToRegister = append(typesToRegister, typ)
	return struct{}{}
}

const customTypesSQL = `SELECT 'some_text', 1::bigint;`

type CustomTypesRow struct {
	Column mytype.String `json:"?column?" db:"?column?"`
	Int8   CustomInt     `json:"int8" db:"int8"`
}

// CustomTypes implements Querier.CustomTypes.
func (q *DBQuerier) CustomTypes(ctx context.Context) (CustomTypesRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CustomTypes")
	rows, err := q.conn.Query(ctx, customTypesSQL)
	if err != nil {
		var zero CustomTypesRow
		return zero, fmt.Errorf("query CustomTypes: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[CustomTypesRow])
	if err != nil {
		var zero CustomTypesRow
		return zero, fmt.Errorf("query CustomTypes: %w", err)
	}
	return result, nil
}

const customStringSQL = `SELECT 'some_text'::text;`

// CustomString implements Querier.CustomString.
func (q *DBQuerier) CustomString(ctx context.Context) (mytype.String, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CustomString")
	rows, err := q.conn.Query(ctx, customStringSQL)
	if err != nil {
		var zero mytype.String
		return zero, fmt.Errorf("query CustomString: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowTo[mytype.String])
	if err != nil {
		var zero mytype.String
		return zero, fmt.Errorf("query CustomString: %w", err)
	}
	return result, nil
}

const customMyIntSQL = `SELECT '5'::my_int as int5;`

// CustomMyInt implements Querier.CustomMyInt.
func (q *DBQuerier) CustomMyInt(ctx context.Context) (int, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CustomMyInt")
	rows, err := q.conn.Query(ctx, customMyIntSQL)
	if err != nil {
		var zero int
		return zero, fmt.Errorf("query CustomMyInt: %w", err)
	}

	result, err := pgx.CollectOneRow(rows, pgx.RowTo[int])
	if err != nil {
		var zero int
		return zero, fmt.Errorf("query CustomMyInt: %w", err)
	}
	return result, nil
}

const intArraySQL = `SELECT ARRAY ['5', '6', '7']::int[] as ints;`

// IntArray implements Querier.IntArray.
func (q *DBQuerier) IntArray(ctx context.Context) ([][]int32, error) {
	ctx = context.WithValue(ctx, QueryName{}, "IntArray")
	rows, err := q.conn.Query(ctx, intArraySQL)
	if err != nil {
		var zero [][]int32
		return zero, fmt.Errorf("query IntArray: %w", err)
	}

	result, err := pgx.CollectRows(rows, pgx.RowTo[[]int32])
	if err != nil {
		var zero [][]int32
		return zero, fmt.Errorf("scan IntArray row: %w", err)
	}
	return result, nil
}
